Repository JohannesValoy/WebShop-Group-12, pull requests merged in 2023-05, with the labels that each got.

#66 Load demo products in prod
  src/main/java/no/ntnu/webshop/group12/webshop/tools/DevInitializer.java
  src/main/java/no/ntnu/webshop/group12/webshop/tools/MinInitilizer.java
Labels: hot fix

#74 Css cleanup
  src/main/resources/static/css/cart.css
  src/main/resources/static/css/category-card.css
  src/main/resources/static/css/product-card.css
  src/main/resources/static/css/style.css
  src/main/resources/templates/cart.html
  src/main/resources/templates/components/cart-products.html
  src/main/resources/templates/components/product-card.html
  src/main/resources/templates/index.html
  src/main/resources/templates/purchase-confirmed.html
  src/main/resources/templates/search.html
Labels: Front-end

#73 Login fix
  src/main/resources/static/css/category-card.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/loginScripts.js
  src/main/resources/templates/login.html
Labels: Front-end

#77 Product page
  pom.xml
  src/main/java/no/ntnu/webshop/group12/webshop/models/product/Product.java
  src/main/java/no/ntnu/webshop/group12/webshop/tools/DevInitializer.java
  src/main/java/no/ntnu/webshop/group12/webshop/tools/MinInitilizer.java
  src/main/resources/application-prod.properties
  src/main/resources/static/css/account.css
  src/main/resources/static/css/card.css
  src/main/resources/static/css/category.css
  src/main/resources/static/css/login.css
  src/main/resources/static/css/product-page.css
  src/main/resources/static/css/product-table.css
  src/main/resources/static/css/style.css
  src/main/resources/static/images/Alex.webp
  src/main/resources/static/images/logo.webp
  src/main/resources/static/js/cart-and-checkout.js
  src/main/resources/static/js/product-page.js
  src/main/resources/templates/about.html
  src/main/resources/templates/account.html
  src/main/resources/templates/cart.html
  src/main/resources/templates/category.html
  src/main/resources/templates/components/footer.html
  src/main/resources/templates/components/head.html
  src/main/resources/templates/components/header.html
  src/main/resources/templates/components/product-card.html
  src/main/resources/templates/components/product-table.html
  src/main/resources/templates/components/webpImage.html
  src/main/resources/templates/error.html
  src/main/resources/templates/index.html
  src/main/resources/templates/login.html
  src/main/resources/templates/product.html
  src/main/resources/templates/purchase-confirmed.html
  src/main/resources/templates/search.html
  src/test/java/no/ntnu/webshop/group12/webshop/controllers/api/ProductControllerTest.java
Labels: Branch, Front-end, Back-end
